### ISSUE TITLE
Support Gradle 2.X

### ISSUE THREAD

**Issue by yogurtearl** [tbroyer/gradle-errorprone-plugin-v0.0.x#4]
Support Gradle 2.X

**Comment by yogurtearl** [comment]
You may have seen this, but here is one of the Gradle 2.x warnings we get:

```
Error listing versions of com.google.errorprone:error_prone_core 
using class org.gradle.api.internal.artifacts.repositories.resolver.MavenVersionLister$1.
 Will attempt an alternate way to list versions. 
This behaviour has been deprecated and is scheduled to be removed in Gradle 2.0
```

**Comment by marshallpierce** [comment]
When running on 1.12, Gradle outputs the following:

```
The Compile.setJavaCompiler(Compiler<JavaCompileSpec>) method has been deprecated and is scheduled to be removed in Gradle 2.0.
```

And sure enough, it's gone in 2.0 so the build fails with a NoSuchMethodError. A little bit of investigation hasn't uncovered a suitable replacement, unfortunately.

**Comment by tbroyer** [comment]
One way is to fork a JVM for the compiler but I haven't been able to make it work due to a classpath issue (I suspect a bug in Gradle, haven't had time to investigate)

**Comment by tbroyer** [comment]
Also, future versions of Gradle will introduce new APIs that will allow using errorprone again.

**Comment by yogurtearl** [comment]
Does Gradle 2.1 have any new API to re-enable error-prone?

**Comment by tbroyer** [comment]
There's a new [`toolchain` property](http://www.gradle.org/docs/current/javadoc/org/gradle/api/tasks/compile/JavaCompile.html#setToolChain%28org.gradle.runtime.jvm.toolchain.JavaToolChain%29) on the `JavaCompile` task. It requires implementing an internal interface (as `JavaToolChain` is hardly more than a marker interface) but should allow integrating error-prone. Let's just hope it won't change too much in future releases (still seems to be compatible with 2.2 from a quick look at the sources; though maybe we'd better be using a `JavaPlatform` going forward)

**Comment by yogurtearl** [comment]
Looking forward to this. I had to remove error-prone when we switched to
Gradle 2.

**Comment by tbroyer** [comment]
Actually, `JavaToolChainInternal` has changed a lot between 2.1 and 2.2-rc1, so let's try to get something working for 2.1 and we'll work on 2.2 support when it's released.

**Comment by tbroyer** [comment]
Just released 0.0.4 with support for Gradle 2.1 (only; see README)
