### ISSUE TITLE
Gradle 2.6 compatibility

### ISSUE THREAD

**Issue by ben-manes** [tbroyer/gradle-errorprone-plugin-v0.0.x#12]
```
* What went wrong:
A problem occurred evaluating root project 'caffeine'.
> org.gradle.api.tasks.compile.JavaCompile.getToolResolver()Lorg/gradle/platform/base/internal/toolchain/ToolResolver;

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'caffeine'.
    at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
    ...
Caused by: java.lang.NoSuchMethodError: org.gradle.api.tasks.compile.JavaCompile.getToolResolver()Lorg/gradle/platform/base/internal/toolchain/ToolResolver;
    at net.ltgt.gradle.errorprone.ErrorPronePlugin$1.execute(ErrorPronePlugin.java:29)
    at net.ltgt.gradle.errorprone.ErrorPronePlugin$1.execute(ErrorPronePlugin.java:26)
    ...

BUILD FAILED
```

**Comment by michel-slm** [comment]
Mine fails at a different point, as soon as the plugin is applied

```
* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'repository'.
    at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
...
Caused by: java.lang.ClassNotFoundException: org.gradle.platform.base.internal.toolchain.ToolResolver
    ... 82 more
```

**Comment by dridi** [comment]
I have the same error as @michel-slm when I use the plugin this way:

``` groovy
plugins {
        id "org.gradle.java"
        id "net.ltgt.errorprone" version "0.0.7.1"
}
```

Edit: applying the plugin this way seems to work fine with gradle 2.4 (not tested with 2.5)

**Comment by tbroyer** [comment]
Just published an 0.0.8 updated for Gradle 2.6; thanks for the reports.
(sorry for the delay, I was on vacations for 2 weeks)

**Comment by coderlindacheng** [comment]
hello,it seems not working again in gradle 3.2 ........ , i am using jdk7,is it mater?

**Comment by CoderLinDaCheng** [comment]
ah..... i work with jdk7

**Comment by tbroyer** [comment]
@CoderLinDaCheng The plugin does work with Gradle 3.2 (proofs, based on the `master` branch though but there are very few changes compared to version 0.0.8, in [Travis CI](https://travis-ci.org/tbroyer/gradle-errorprone-plugin/jobs/181291707) and [App Veyor](https://ci.appveyor.com/project/tbroyer/gradle-errorprone-plugin))

If you confirm it doesn't work for you, could you please open a new issue?
(I'm assuming you correctly configured Gradle to use a version of Error Prone compatible with Java 7; i.e. at most 2.0.5)
